@startuml LOTRGame




package game{
    Class LOTRGame{
        -Turns turns

        +LOTRGame()
        +void execute()

    }
    Class Armies{
        -ArrayList<Character> squadA
        -ArrayList<Character> squadB

        +Armies()
        +void createArmie()
        +void fight()
    }

    Class Turns{
        -Armies armies

        +startTurns()

    }

    package interfaces{

        interface Fighter{
            +Attack getInstance()

            +int getAttack()
            +int defend()

        }

        interface AttackCalculator{
            +int getAttack()
         }

        interface DefendCalculatore{
            +int defend()
        }




    }


    package gameCharacters{

        Abstract Class Characters{
            #int armor
            #String name
            #int healthPoint

            +int randomPower(int limit)
            +int getArmor()
            +String getName()
            +int getHealthPoint()
            +void getHealthPoint()

        }

        package heroes{
            Class Elves{
                +final int hateAgainstOrcs
            }

            Class Hobbits{
                +final int fearAgainstTrasgos
            }
            Class Human{

            }


        }

        package beasts{


            Class Orcs{
                +int strengthBonusAgainstAll
            }
            Class Trasgos{
            }

        }

    }
}



LOTRGame *-- Turns
LOTRGame *-- Armies

Turns --> Armies

Armies *-- Characters

Characters .up.> Fighter

Fighter <|.. AttackCalculator
Fighter <|.. DefendCalculatore


Characters <|-- Elves
Characters <|-- Hobbits
Characters <|-- Human

Characters <|-- Orcs
Characters <|-- Trasgos



@enduml